name: xylophone
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: "3.0.6"

dependencies:
  flutter:
    sdk: flutter

#  cupertino_icons: ^0.1.2

  audioplayers: ^5.1.0
  google_fonts: ^5.1.0
  http: ^1.1.0
  # Use Audioplayers dependency version 0.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/note1.wav
    - assets/note2.wav
    - assets/note3.wav
    - assets/note4.wav
    - assets/note5.wav
    - assets/note6.wav
    - assets/note7.wav


